{% set version = "0.4.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geometry
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geometry_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geometry/geometry_{{ version }}.tar.gz
  sha256: 910465a8c8043faca73bcc7c81c9249b9938677ee6649468003b438a6503f5d8

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcppprogress
    - r-linprog
    - r-lpsolve
    - r-magic
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-rcppprogress
    - r-linprog
    - r-lpsolve
    - r-magic

test:
  commands:
    - $R -e "library('geometry')"           # [not win]
    - "\"%R%\" -e \"library('geometry')\""  # [win]

about:
  home: https://davidcsterratt.github.io/geometry
  license: GPL-3.0-or-later
  summary: Makes the 'Qhull' library <http://www.qhull.org> available in R, in a similar manner as in Octave and MATLAB. Qhull computes convex hulls, Delaunay triangulations, halfspace intersections about a point, Voronoi diagrams, furthest-site Delaunay triangulations, and furthest-site Voronoi diagrams. It runs in 2D,
    3D, 4D, and higher dimensions. It implements the Quickhull algorithm for computing the convex hull. Qhull does not support constrained Delaunay triangulations, or mesh generation of non-convex objects, but the package does include some R functions that allow for this.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: geometry
# License: GPL (>= 3)
# Title: Mesh Generation and Surface Tessellation
# Authors@R: c( person("Jean-Romain", "Roussel" , role=c("cph", "ctb"), comment = "wrote tsearch function with QuadTrees"), person("C. B.", "Barber" , role="cph"),  person("Kai", "Habel", role=c("cph","aut")),  person("Raoul", "Grasman", role=c("cph","aut")), person("Robert B.", "Gramacy", role=c("cph","aut")), person("Pavlo", "Mozharovskyi", role=c("cph","aut")), person("David C.", "Sterratt", role=c("cph","aut","cre"), email="david.c.sterratt@ed.ac.uk", comment=c(ORCID="0000-0001-9092-9099")))
# Description: Makes the 'Qhull' library <http://www.qhull.org> available in R, in a similar manner as in Octave and MATLAB. Qhull computes convex hulls, Delaunay triangulations, halfspace intersections about a point, Voronoi diagrams, furthest-site Delaunay triangulations, and furthest-site Voronoi diagrams. It runs in 2D, 3D, 4D, and higher dimensions. It implements the Quickhull algorithm for computing the convex hull. Qhull does not support constrained Delaunay triangulations, or mesh generation of non-convex objects, but the package does include some R functions that allow for this.
# Version: 0.4.4
# URL: https://davidcsterratt.github.io/geometry
# Date: 2019-08-27
# BugReports: https://github.com/davidcsterratt/geometry/issues
# Depends: R (>= 3.0.0)
# Imports: magic, Rcpp, lpSolve, linprog
# Suggests: spelling, testthat, rgl, R.matlab, tripack
# RoxygenNote: 6.1.1
# LinkingTo: Rcpp, RcppProgress
# Encoding: UTF-8
# Language: en-GB
# NeedsCompilation: yes
# Packaged: 2019-09-03 10:39:24 UTC; sterratt
# Author: Jean-Romain Roussel [cph, ctb] (wrote tsearch function with QuadTrees), C. B. Barber [cph], Kai Habel [cph, aut], Raoul Grasman [cph, aut], Robert B. Gramacy [cph, aut], Pavlo Mozharovskyi [cph, aut], David C. Sterratt [cph, aut, cre] (<https://orcid.org/0000-0001-9092-9099>)
# Maintainer: David C. Sterratt <david.c.sterratt@ed.ac.uk>
# Repository: CRAN
# Date/Publication: 2019-09-03 13:40:06 UTC
