{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geometry
  version: {{ version|replace("-", "_") }}

source:
  fn: geometry_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/geometry_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geometry/geometry_{{ version }}.tar.gz
  sha256: 1ec4c1fe06ca0cfc8a542913de4144af24ec8cfbe8ec966710e0cb915480f152

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-magic
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-magic

test:
  commands:
    - $R -e "library('geometry')"           # [not win]
    - "\"%R%\" -e \"library('geometry')\""  # [win]

about:
  home: http://geometry.r-forge.r-project.org/
  license: GPL (>= 3)
  summary: Makes the qhull library (www.qhull.org) available in R, in a similar manner as in
    Octave and MATLAB. Qhull computes convex hulls, Delaunay triangulations, halfspace
    intersections about a point, Voronoi diagrams, furthest-site Delaunay triangulations,
    and furthest-site Voronoi diagrams. It runs in 2-d, 3-d, 4-d, and higher dimensions.
    It implements the Quickhull algorithm for computing the convex hull. Qhull does
    not support constrained Delaunay triangulations, or mesh generation of non-convex
    objects, but the package does include some R functions that allow for this. Currently
    the package only gives access to Delaunay triangulation and convex hull computation.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
