appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: b+iLI253jdkSg0MghKI+Fikb+9IYw8L0gju1FlXExDnRj65TYQOQlNzre1ws7wZ+ZmGcurGssEYgwByv49S8eFP4q+mJRk9DuOvsB0qd7fZbsCV2fv9NHg+LlA1MBjihicAXUesNpcg47V472lFn6LC/b19adzcRvI4kLWKD6KMyAAl6JNDs957YaoeknJZgNLpKRXCNfiWw+2sWp5Wv/DKBj9IBfymLY4ftR7ppz716BTGTqQO0XRLVRXJ2UTdKUFmYQ1qC1cH+7iHYFmNUGZ8/PLGRFp+zTNeXg6OwF+ltE0FgWfMpt5zSICI4ylldvBbExNYDp6gUiknbRDyw5+3U16emdlhX5id0cATwyc4gj0MHF0wRRR1n+AlbkHnQG81IUkc+24MqOt9eAMTsuCr+MojjSQe0oIIoNu8fPJaoacRuq3kuZysHkAn7yw/V83PrdFvGvoaJf7vJOU4uZ9Tn05Z83lyzXyCvWdkzZJuKuUfwTCeQa0uNXVWDPjcJDjvW05iEwgVqUCstcifwAkBduG7uWlBYSnt9orwwx7U681+0ZmyuPfuBTp9dfyWyPS4fTcdSF4o09gMk+jm3OhIw0iLiX7rmfwSo5Outm2JzWWOkZf4+a06JQ1TF8sm2WKHUsp4wYLRvx0SMBSp/BIbCSN4vRNW7WDAdQeixBqU=}
