travis:
  secure:
    BINSTAR_TOKEN: p4YG5YUHlKEWwuviIKCDRFt2VCRsdOUYf8irltWb5DAb85nXVVbKqfvTUyL2kwOjOO0w7asQe/mgba/iTXInvC5jyksvZDKzGNs3lMHEQ9G3sRVW8u7Pkj/tKLUMm+Ljl+hVJqrIbiOxCYt9TBRJ/0wu7WGpSg9mkgBWQkGxKFm6nskE044KLNV/c8Cv9gzfmcnlNaQzex3Iw3qBdZ39OCeu9FzDyDd2BbOTVTG1M5Q43PFC1Vt8MFYidDks3aJpLhj0WzA+3Di4buya9badGVmKnDNBst+qC7w6bm/3nFM6TQSwMbKfVYkieqfClpvJ7Wrwa2KysS6TXXwddpKmbmebSuTJOd5jTmKaQI/KVeR/8keDBYJhZDVvGd3yBLEAQhabuqppAGFwjbJQDZIuRKqvO9Foh6rGBbzNhhzikU8cCdTPZcrx1czaUFAgNzU7zJkPmgnN5NwYf0GlL6Opmajh4IojlnooVedC/MFhFbRccysO620oG5J4fqSjZ0G9RrRmr2baO6+W/Q99+fbDhU8JhszLnMlqRVWOGzZ8cwUMBrF7l48PzcB4Lz2ixJ3GBYyWRB829EO6C8AaQ8lLCIzp3fJjDCrkESWBQOaPQGcbUKXNTJk7o3wGRwiCMiKj2XcUV2f1EaPyNE4u+GRbf6aISeIIUX25rwoYMoJfAbI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
